name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Enable Corepack
        run: corepack enable

      - name: Install Yarn
        run: corepack prepare yarn@4.5.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn build
        env:
          CI: true

      - name: Test
        run: |
          yarn ci
        env:
          CI: true

      - name: Build Docs
        run: |
          yarn build-docs
        env:
          CI: true

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist/ngx-datatable
        if: ${{ github.ref == 'refs/heads/master' }}
